version: "3"
services:
    elasticsearch:
      image: elasticsearch:7.17.10
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - discovery.type=single-node
    kibana:
      image: kibana:7.17.10
      ports:
        - "5601:5601"
      links:
        - elasticsearch
      depends_on:
        - elasticsearch
    apm-server:
      image: elastic/apm-server:7.17.10
      ports:
        - "8200:8200"
      volumes:
        - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
      depends_on:
        - elasticsearch
      links:
        - elasticsearch
        - kibana
    ads-user:
      build:
        context: .
        dockerfile: Dockerfile
      image: ads-user:latest
      ports:
        - "8000:8000"
      volumes:
        - ./keys:/opt/ads-user/keys
      environment:
        - ELASTIC_APM_SERVER_URL=http://apm-server:8200
