name: tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
      
      - name: check go.mod
        run: |
          set -e
          go mod tidy
          output=$(git status -s)
          if [ -z "${output}" ]; then
            exit 0
          fi
          echo "$output"
          exit 1

      - name: fmt check
        run: |
          set -e
          files=$(gofmt -l .)
          if [ -z "${files}" ]; then
            exit 0
          fi
          echo "$files"
          exit 1

      - name: run tests
        run: |
          go test ./...
